### ISSUE TITLE
The : in filenames forces a rename in Windows

### ISSUE THREAD

**Issue by TheAntVenom** [safijari/decky-recorder-fork#1]
Someone in the Deck Homebrew Discord mentioned this, but apparently a new filename addition includes colons, which are illegal for filenames in Windows, prompting the files to individually require renaming when transferring them to Windows. Any chance of changing out the usage of that character?

**Comment by safijari** [comment]
Yes I can work on that.

**Comment by safijari** [comment]
Implemented in https://github.com/safijari/decky-recorder-fork/commit/2a438cfe9ffba13d50ca1052641557edee5ff65b
