### ISSUE TITLE
Doesn't work at all on latest update

### ISSUE THREAD

**Issue by LuisMayo** [safijari/decky-recorder-fork#20]
Nor Repay or record modes. Tested on 3.4 and 3.5 :(

No error messages are shown for record mode, they're for replay mode ("too soon to record another clip")

**Comment by SubstituteDoll** [comment]
I realize I am not the dev here, but I just tested it without any issues. Could you please provide the steps to recreate it?

**Comment by LuisMayo** [comment]
This foes not longer happen since the last update so I'll mark it as fixed
