### ISSUE TITLE
Recordings from the game Fate/Samurai Remnant are not saved

### ISSUE THREAD

**Issue by unosofmanila** [safijari/decky-recorder-fork#24]
I just noticed that this plug-in doesn't work for the game Fate/Samurai Remnant.
The notification, when I try to save replay, says "clip saved" but no video is generated in the directory.

I'm just assuming here, but I imagine it's because of the forward slash in the game's title.
Filenames for the screenshot uses the game's title and an error probably happens which ends up the files not being saved. Took me 10 hours to realize my replays are not being saved, so if my recordings actually ended up somewhere that's not "home/deck/videos", please tell me.

**Comment by safijari** [comment]
Oof. Sorry about this. Unless there's a folder in Videos called "Fate", your recordings are probably lost. I'll add a way to sanitize the filename so this doesn't happen again.

**Comment by safijari** [comment]
Should be fixed in latest version
