### ISSUE TITLE
Replay options grayed out

### ISSUE THREAD

**Issue by martinsaenz96** [safijari/decky-recorder-fork#8]
I don't know if I'm the only one with this issue, but every time I wanna record the last 30 seconds or 5 minutes of game play, the options are all grayed out. While other times it works. 90% of the time it doesn't work, any idea why?

**Comment by safijari** [comment]
There's a known issue where if you had the option on when you rebooted, it turns on but does not successfully start recording. You have to turn it off an on again.

I'm hoping to fix next time I get some time to work on this.

**Comment by martinsaenz96** [comment]
I do just that and still nothing. It gets annoying and I hope this gets patched up soon (and maybe have the ability to leave replay mode on as default while simultaneously have the record feature for when I wanna start recording at anytime).
